# Generated by Django 6.0.5 on 2026-05-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('estrelas', models.IntegerField(default=5)),
                ('foto_cliente', models.ImageField(blank=True, null=True, upload_to='depoimentos/')),
                ('exibir_no_site', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('BOX', 'Box de Banheiro'), ('SACADA', 'Fechamento de Sacada'), ('ESPELHO', 'Espelhos'), ('VIDRO', 'Vidro Temperado/Laminado')], max_length=10)),
                ('imagem', models.ImageField(upload_to='portfolio/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('url_video', models.URLField(help_text='Insira o link do YouTube ou Vimeo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
