# Generated by Django 6.0.5 on 2026-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_redessociais'),
    ]

    operations = [
        migrations.AddField(
            model_name='redessociais',
            name='youtube',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
