# Generated by Django 6.0.5 on 2026-05-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_redessociais_youtube'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_rodape', models.CharField(blank=True, default='STYLLO VIDROS', max_length=100, null=True)),
                ('descricao_rodape', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuração do Rodapé',
                'verbose_name_plural': 'Configurações do Rodapé',
            },
        ),
    ]
