# Generated by Django 6.0.5 on 2026-06-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_album_albumfoto_album_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-criado_em']},
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='data_envio',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='email',
        ),
        migrations.AddField(
            model_name='contato',
            name='servico',
            field=models.CharField(blank=True, default='Geral', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='whatsapp',
            field=models.CharField(max_length=25),
        ),
    ]
