# Generated by Django 6.0.5 on 2026-06-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_contato_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.categoria'),
        ),
    ]
